comment: false

ignore:
  - "^.*Models.*$"
  - "^.*Migrations.*$"
  - "^.*Infrastructure.*$"
  - "^.*Domain.Services.UserManager.*$"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
